name: BukkitInventoryTools
main: dk.gabriel333.BukkitInventoryTools.BIT
version: 2.9.1
author: Gabriel333
authors: [Rocoloco]
website: http://dev.bukkit.org/server-mods/bukkitinventorytools/
dev-url: https://github.com/BukkitInventoryTools
description: Shop, Digital lock, sort and stack inventories
depend: [Spout]
softdepend: 
commands:
    sort:
        description: Rebuild all item stack in your inventory.
        usage: /sort
        aliases: si 
        permission: bukkitinventorytools.sortinventory.use
    digilock:
        description: Lock the item with a digital pincode.
        usage: /digilock [pincode]|[unlock pincode]|[lock pincode]|[owner playername]|[closetimer seconds]|[usecost cost]|[remove]|[addcoowner name]|[remcoowner name]|[adduser name]|[remuser name]|[info]
        aliases: dlock
        permission: bukkitinventorytools.digilock.use
    bookshelf:
        description: Create and use a Bookshelf inventory.
        usage: /bookshelf []|[create inventoryname]|[owner playername]|[usecost cost]|[remove]|[addcoowner name]|[remcoowner name]|[info]
        aliases: bs
        permission: bukkitinventorytools.bookshelf.use
    backpack:
        description: Wear a backpack.
        usage: /backpack
        aliases: bp
        permission: bukkitinventorytools.backpack.use
permissions:
    bukkitinventorytools.sortinventory.use:
        default: true
    bukkitinventorytools.sortinventory.stack.tools:
        default: op
    bukkitinventorytools.sortinventory.stack.armor:
        default: op
    bukkitinventorytools.sortinventory.stack.weapons:
        default: op
    bukkitinventorytools.sortinventory.stack.food: 
        default: op
    bukkitinventorytools.sortinventory.stack.vehicles:
        default: op
    bukkitinventorytools.sortinventory.stack.buckets:
        default: op
    bukkitinventorytools.digilock.create:
        default: true
    bukkitinventorytools.digilock.use:
        default: true
    bukkitinventorytools.digilock.admin:
        default: op
    bukkitinventorytools.bookshelf.create:
        default: true
    bukkitinventorytools.bookshelf.use:
        default: true
    bukkitinventorytools.bookshelf.admin:
        default: op
    bukkitinventorytools.book.create:
        default: true
    bukkitinventorytools.book.use:
        default: true
    bukkitinventorytools.book.admin:
        default: op
    bukkitinventorytools.backpack.use:
        default: true
    bukkitinventorytools.backpack.size9:
        default: true
    bukkitinventorytools.backpack.size18:
        default: false
    bukkitinventorytools.backpack.size27:
        default: false
    bukkitinventorytools.backpack.size36:
        default: false
    bukkitinventorytools.backpack.size45:
        default: false
    bukkitinventorytools.backpack.size54:
        default: op
    bukkitinventorytools.backpack.upgrade18:
        default: false
    bukkitinventorytools.backpack.upgrade27:
        default: false
    bukkitinventorytools.backpack.upgrade36:
        default: false
    bukkitinventorytools.backpack.upgrade45:
        default: false
    bukkitinventorytools.backpack.upgrade54:
        default: false
    bukkitinventorytools.backpack.clear:
        default: true
    bukkitinventorytools.backpack.workbench:
        default: true
    bukkitinventorytools.backpack.reload:
        default: op
    bukkitinventorytools.backpack.nodrop:
        default: op
    bukkitinventorytools.backpack.info.other:
        default: op
    bukkitinventorytools.backpack.clear.other:
        default: op
    bukkitinventorytools.backpack.open.other:
        default: op



