name: BukkitInventoryTools
main: dk.gabriel333.BukkitInventoryTools.BIT
version: 2.0.4
author: Gabriel333
website: https://github.com/BukkitInventoryTools
description: Use /sort to sort you personal inventory or the chest
depend: [Spout]
commands:
    sort:
        description: Rebuild all item stack in your inventory.
        usage: /sort
        aliases: /sortinventory 
        permission: bukkitinventorytools.sortinventory.use
    digilock:
        description: Lock the item with a digital pincode.
        usage: /digilock [owner owner]|[pincode code]|[reset]|[remove]|[closetimer seconds]
        aliases: /dlock 
        permission: bukkitinventorytools.digilock.use
permissions:
    bukkitinventorytools.sortinventory.use:
        default: true
    bukkitinventorytools.sortinventory.stack.tools:
        default: op
    bukkitinventorytools.sortinventory.stack.armor:
        default: op
    bukkitinventorytools.sortinventory.stack.weapons:
        default: op
    bukkitinventorytools.sortinventory.stack.food: 
        default: op
    bukkitinventorytools.sortinventory.stack.vehicles:
        default: op
    bukkitinventorytools.digilock.use:
        default: true
    bukkitinventorytools.digilock.admin:
        default: op
