name: BukkitInventoryTools
main: dk.rocologo.BukkitInventoryTools.BIT
version: 1.0
author: Rocologo, Gabriel333
website: https://github.com/BukkitInventoryTools
description: Use /sort to sort you personal inventory or the chest
depend: [Spout]
commands:
    sort:
        description: Rebuild all item stack in your inventory.
        usage: /sort
        aliases: /sortinventory 
        permission: bit.sortinventory.use
    digilock:
        description: Lock the item with a digital pincode.
        usage: /digilock [owner owner]|[pincode code]|[reset]|[remove]|[closetimer seconds]
        aliases: /dlock 
        permission: bit.digilock.use
permissions:
    bit.sortinventory.use:
        default: true
    bit.sortinventory.stack.tools:
        default: op
    bit.sortinventory.stack.armor:
        default: op
    bit.sortinventory.stack.weapons:
        default: op
    bit.sortinventory.stack.food: 
        default: op
    bit.sortinventory.stack.vehicles:
        default: op
    bit.digilock.use:
        default: true
    bit.digilock.use:
        default: OP
