name: BukkitInventoryTools
main: dk.gabriel333.BukkitInventoryTools.BIT
version: 2.1.6
author: Gabriel333
website: https://github.com/BukkitInventoryTools
dev-url: http://dev.bukkit.org/server-mods/bukkitinventorytools/
description: Digital lock, sort and stack inventories
depend: [Spout]
commands:
    sort:
        description: Rebuild all item stack in your inventory.
        usage: /sort
        aliases: /sortinventory 
        permission: bukkitinventorytools.sortinventory.use
    digilock:
        description: Lock the item with a digital pincode.
        usage: /digilock [pincode]|[unlock pincode]|[lock pincode]|[owner playername]|[closetimer seconds]|[remove]
        aliases: /dlock
        permission: bukkitinventorytools.digilock.use
permissions:
    bukkitinventorytools.sortinventory.use:
        default: true
    bukkitinventorytools.sortinventory.stack.tools:
        default: op
    bukkitinventorytools.sortinventory.stack.armor:
        default: op
    bukkitinventorytools.sortinventory.stack.weapons:
        default: op
    bukkitinventorytools.sortinventory.stack.food: 
        default: op
    bukkitinventorytools.sortinventory.stack.vehicles:
        default: op
    bukkitinventorytools.sortinventory.stack.buckets:
        default: op
    bukkitinventorytools.digilock.use:
        default: true
    bukkitinventorytools.digilock.admin:
        default: op
